In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
DATADIR = "/content/drive/My Drive/Colab Notebooks/test10.csv"
df = pd.read_csv(DATADIR)

In [ ]:
len(df)

4287

In [ ]:
df['Classes'].value_counts()

Sad      1537
Anger    1436
Joy      1314
Name: Classes, dtype: int64

In [ ]:
df[:5]

Text Classes
0  ইহার পরেও বুদ্ধিমান সিরিয়াস মানুষের মনে কোন জি...     Sad
1              জগতে এই জাতীয় ঘটনা হামেশা ঘটতেই থাকবে     Sad
2                            তাতে তার কিই বা আসে যায়     Sad
3                      পেটে সয় না তো এতগুলো খেলে কেন   Anger
4                                     একেই বলে অভাগা     Sad

##Data Cleaning##

In [ ]:
pip install BnPreprocessing

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import BnPreprocessing as pp
df['preprocessed_text'] = df['Text'].apply(lambda x: pp.remove_noise(str(x)))

 

In [ ]:
df[20:3000]

Text Classes  \
20                         নাই মামার ছেয়ে কানা মামা ভাল     Joy   
21                               মানুষের চেতনার বড় অভাব     Sad   
22                  ছোট হলেও সে বেশ বুঝে কে তার ভাল চায়     Joy   
23                                অনেক বেশি পাল্টে গেছো     Sad   
24    এই ফুলগুলোর সৌন্দর্যের তীব্র ঝাপটায় বন্ধ হয়ে আ...     Joy   
...                                                 ...     ...   
2995  এ সব প্রকল্পের জন্য নিন্দা জানাই,,,ঐ দিকে নদী ...   Anger   
2996  বিশেষজ্ঞরা শুধু সমস্যাই দেখাতে পারবে কোনো সমাধ...   Anger   
2997           জনগণকে ফকির বানিয়ে হরিলুট করার পরিকল্পনা   Anger   
2998  ঘরের মধ্যে দিয়ে রেল দে ব্যাটা শালারা... অথবা প...   Anger   
2999  আপনি আসার পর আজগুবী কিছু সিদ্ধান্ত নিয়ে কল রেট...   Anger   

                                      preprocessed_text  
20                             মামার ছেয়ে কানা মামা ভাল  
21                               মানুষের চেতনার বড় অভাব  
22                                     ছোট বুঝে ভাল চায়  
23                                          পাল্টে গেছো  
24    ফুলগুলোর সৌন্দর্যের তীব্র ঝাপটায় বন্ধ হয়ে আসছি...  
...                                                 ...  
2995  প্রকল্পের নিন্দা জানাই নদী ভাঙনের ভিটে মাটি হা...  
2996       বিশেষজ্ঞরা সমস্যাই দেখাতে পারবে সমাধান পারবে  
2997                জনগণকে ফকির বানিয়ে হরিলুট পরিকল্পনা  
2998  ঘরের দিয়ে রেল ব্যাটা শালারা পাইপ বসা ওয়াসার প্...  
2999  আসার আজগুবী সিদ্ধান্ত কল রেট বাড়ায়া দিছেন ইন্ট...  

[2980 rows x 3 columns]

In [ ]:
l = ['aaaaaaaa']
#l = ['মানুষের', 'দেশের', 'দেশ', 'মানুষ', 'আপনাদের', 'আপনাদের', 'এসব', 'দেশে', 'বাংলাদেশের' , 'বাংলাদেশ', 'খুবই','এরকম', 'এগুলো','যায়', 'কথা', 'ভাই', 'টাকা', 'দিয়ে', 'হয়ে']
df['more_processed_text'] = df['preprocessed_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (l)]))
df[2000:3500]


Text Classes  \
2000  এতেই প্রমাণ হয় যে, পরিবেশ দূষণের জন্য আমরা মা...   Anger   
2001  আমরা যে কি ভুল করতাম প্রকৃতির উপর তা চোখে আঙুল...   Anger   
2002                                 পৃথিবী সুস্থ হচ্ছে     Joy   
2003                                 মানুষ অসুস্থ হচ্ছে     Sad   
2004  এখন আমাদের গণমাধ্যমকর্মীরা সিদ্ধান্ত নিবে আমরা...   Anger   
...                                                 ...     ...   
3495  কেউ যদি অবিশ্বাসী হন, আল্লাহ তায়ালা তার শাস্ত...   Anger   
3496                                        ফালতু মেয়ে৷   Anger   
3497         নাস্তিকের বাচ্চা নাস্তিক! জাহান্নামের কিট।   Anger   
3498  ওরে বাবা! কী বিশাল বোঝা মাথায় তুলেছে। হয়েছে, অ...   Anger   
3499  খুবই সঠিক পদক্ষেপ। পাশাপাশি আমাদের মন্ত্রীদের ...     Joy   

                                      preprocessed_text  \
2000            এতেই প্রমাণ পরিবেশ দূষণের মানুষরাই দায়   
2001    ভুল করতাম প্রকৃতির চোখে আঙুল দিয়ে দেখিয়ে দিচ্ছে   
2002                                       পৃথিবী সুস্থ   
2003                                       মানুষ অসুস্থ   
2004  গণমাধ্যমকর্মীরা সিদ্ধান্ত নিবে পশ্চিমাদের সাথে...   
...                                                 ...   
3495  অবিশ্বাসী আল্লাহ তায়ালা শাস্তি বিধান ধর্ষকামী...   
3496                                        ফালতু মেয়ে৷   
3497           নাস্তিকের বাচ্চা নাস্তিক জাহান্নামের কিট   
3498       ওরে বাবা বিশাল বোঝা মাথায় তুলেছে হয়েছে হয়েছে   
3499  খুবই সঠিক পদক্ষেপ পাশাপাশি মন্ত্রীদের সেনসেবল ...   

                                    more_processed_text  
2000            এতেই প্রমাণ পরিবেশ দূষণের মানুষরাই দায়  
2001    ভুল করতাম প্রকৃতির চোখে আঙুল দিয়ে দেখিয়ে দিচ্ছে  
2002                                       পৃথিবী সুস্থ  
2003                                       মানুষ অসুস্থ  
2004  গণমাধ্যমকর্মীরা সিদ্ধান্ত নিবে পশ্চিমাদের সাথে...  
...                                                 ...  
3495  অবিশ্বাসী আল্লাহ তায়ালা শাস্তি বিধান ধর্ষকামী...  
3496                                        ফালতু মেয়ে৷  
3497           নাস্তিকের বাচ্চা নাস্তিক জাহান্নামের কিট  
3498       ওরে বাবা বিশাল বোঝা মাথায় তুলেছে হয়েছে হয়েছে  
3499  খুবই সঠিক পদক্ষেপ পাশাপাশি মন্ত্রীদের সেনসেবল ...  

[1500 rows x 4 columns]

In [ ]:
import re
sentences = df['preprocessed_text'].values
print(re.sub(' +', ' ',sentences[0]).split(' '))

['ইহার', 'বুদ্ধিমান', 'সিরিয়াস', 'মানুষের', 'জিজ্ঞাসা', 'চিহ্ন', 'জাগেনা']


In [ ]:
target = df['Classes'].values
print(target[:3])

['Sad' 'Sad' 'Sad']


In [ ]:
map_class = dict(zip(df.Classes.astype("category").cat.codes,df.Classes))
print(map_class)

{2: 'Sad', 0: 'Anger', 1: 'Joy'}


In [ ]:
word_count = {'Anger':{}, 'Sad':{}, 'Joy':{}}

map_class[0]
df_reset = df.reset_index()

for index, row in df_reset.iterrows():
  for word in re.sub(' +', ' ', row['preprocessed_text']).split(' '):
    if word in word_count[row['Classes']].keys():
      word_count[row['Classes']][word]+=1
    else:
      word_count[row['Classes']][word] = 1

print(sorted(word_count['Sad'].items(), key=lambda x: x[1], reverse = True))
print(sorted(word_count['Anger'].items(), key=lambda x: x[1], reverse = True))
print(sorted(word_count['Joy'].items(), key=lambda x: x[1], reverse = True))

[('মানুষ', 135), ('মানুষের', 90), ('কষ্ট', 85), ('হয়ে', 81), ('দেশে', 73), ('দেশের', 68), ('একটা', 66), ('যায়', 54), ('কথা', 54), ('খারাপ', 50), ('বাংলাদেশের', 49), ('জীবন', 48), ('বড়', 40), ('বিচার', 40), ('ভাই', 40), ('দেশ', 38), ('খুবই', 38), ('একজন', 35), ('বাংলাদেশ', 34), ('ভালো', 32), ('সময়', 31), ('টাকা', 30), ('দিয়ে', 29), ('দাম', 29), ('এসব', 28), ('অবস্থা', 28), ('দুঃখ', 27), ('ঘটনা', 26), ('সবাই', 26), ('সাথে', 26), ('দুঃখজনক', 26), ('সমস্যা', 26), ('কারণে', 25), ('মারা', 24), ('হয়েছে', 24), ('সরকার', 23), ('পানি', 23), ('শুনে', 23), ('বছর', 23), ('বাংলাদেশে', 23), ('লাগে', 22), ('আরো', 22), ('এভাবে', 22), ('আইন', 22), ('আল্লাহ', 21), ('এতো', 20), ('ছেলে', 19), ('গেলো', 19), ('অভাব', 18), ('গুলো', 18), ('বিষয়', 18), ('দেখার', 18), ('পুলিশ', 18), ('হয়তো', 17), ('কারন', 17), ('ভাল', 17), ('চোখে', 17), ('ভুল', 16), ('সঠিক', 16), ('শিক্ষা', 16), ('নাম', 16), ('ছিলো', 16), ('কষ্টে', 16), ('আছি', 16), ('কতটা', 16), ('কষ্টের', 16), ('আফসোস', 15), ('আশা', 15), ('দুর্নীতি', 15), ('অস

In [ ]:
df.isnull().sum()

Text                   0
Classes                0
preprocessed_text      0
more_processed_text    0
dtype: int64

**Feature Extraction Using Tf-Idf s**

---



---



In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [ ]:
def tokenizer(text):
    return text.split()

In [ ]:

#vectorizer = CountVectorizer()

#bag = vectorizer.fit_transform(docs)

#print(vectorizer.get_feature_names())

#print(vectorizer.vocabulary_)

#print(bag.toarray())

In [ ]:
uni_df = TfidfVectorizer(tokenizer = tokenizer, ngram_range=(1,1), max_df = 0.06, min_df = 0.0006)
uni_bi_df = TfidfVectorizer(tokenizer = tokenizer, ngram_range=(1,2), max_df = 0.06, min_df = 0.0006)
uni_bi_tri_df = TfidfVectorizer(tokenizer = tokenizer, ngram_range=(1,3), max_df = 0.06, min_df = 0.0006)

X_uni = uni_df.fit_transform(sentences)
X_uni_bi = uni_bi_df.fit_transform(sentences)
X_uni_bi_tri = uni_bi_tri_df.fit_transform(sentences)

In [ ]:
print(X_uni)


<bound method _cs_matrix.toarray of <4287x2202 sparse matrix of type '<class 'numpy.float64'>'
	with 19623 stored elements in Compressed Sparse Row format>>


In [ ]:
pip install mlscorer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import mlscorer as ms

In [ ]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier,VotingClassifier,BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
def get_scores(y_test, y_pred):
        from sklearn.metrics import accuracy_score,f1_score, precision_score, recall_score,confusion_matrix
          # accuracy: (tp + tn) / (p + n)
        accuracy = accuracy_score(y_test, y_pred)
          # f1: 2 tp / (2 tp + fp + fn)
        f1 = f1_score(y_test, y_pred, average = None)
          # precision:  tp / (tp + fp)
        precision = precision_score(y_test, y_pred, average = None)
          # recall:  tp / (tp + fn)
        recall = recall_score(y_test, y_pred, average = None)
        confusion_matrix = confusion_matrix(y_test, y_pred)
        print('confusion_matrix:\n {}'.format(confusion_matrix))
        print('precision: {}'.format(precision))
        print('recall: {}'.format(recall))
        print('fscore: {}'.format(f1))
        # print('support: {}'.format(support))          
        return 0

In [ ]:
def get_f1score(y_test, y_pred):
      from sklearn.metrics import f1_score
      f1score = {}
      list = ["Joy","Sad","Anger"]
      f1 = f1_score(y_test, y_pred, average = None)
      for i in range(0,3):
        f1score[list[i]] = f1[i]
      f1_dict.append(f1score)

In [ ]:
from pandas.core.common import random_state


def get_model1(X_train, X_test, y_train, y_test):
          classifier = SVC(kernel = 'linear', random_state = 0)
          classifier.fit(X_train, y_train)
          y_pred = classifier.predict(X_test)
          print("Results for SVC model : ")
          get_scores(y_test, y_pred)
          ms.get_score_table(y_test, y_pred, map_class)
          get_f1score(y_test, y_pred)

def get_model2(X_train, X_test, y_train, y_test):
          classifier = KNeighborsClassifier(n_neighbors=5)
          classifier.fit(X_train, y_train)
          y_pred = classifier.predict(X_test)
          print("Results for knn model : ")
          get_scores(y_test, y_pred)
          ms.get_score_table(y_test, y_pred, map_class)
          get_f1score(y_test, y_pred)

def get_model3(X_train, X_test, y_train, y_test):
          classifier = LogisticRegression(random_state=0).fit(X_train, y_train)
          y_pred = classifier.predict(X_test)
          print("Results for LogisticRegression model : ")
          get_scores(y_test, y_pred)
          ms.get_score_table(y_test, y_pred, map_class)
          get_f1score(y_test, y_pred)

def get_model4(X_train, X_test, y_train, y_test):
          classifier = MultinomialNB()
          classifier.fit(X_train, y_train)
          y_pred = classifier.predict(X_test)
          print("Results for Naive bayes model : ")
          get_scores(y_test, y_pred)
          ms.get_score_table(y_test, y_pred, map_class)
          get_f1score(y_test, y_pred)
    
def get_model5(X_train, X_test, y_train, y_test):
          classifier = RandomForestClassifier(n_estimators=200, random_state=0)
          classifier.fit(X_train, y_train)
          y_pred = classifier.predict(X_test)
          print("Results for Random Forest model : ")
          get_scores(y_test, y_pred)
          ms.get_score_table(y_test, y_pred, map_class)
          get_f1score(y_test, y_pred)



def get_model6(X_train, X_test, y_train, y_test):
          classifier = DecisionTreeClassifier(random_state=0)

          classifier.fit(X_train, y_train)
          y_pred = classifier.predict(X_test)
          print("Results for Decision Tree Model : ")
          get_scores(y_test, y_pred)
          ms.get_score_table(y_test, y_pred, map_class)
          get_f1score(y_test, y_pred)


def get_model8(X_train, X_test, y_train, y_test):
          classifier = BaggingClassifier(LogisticRegression(),
                        n_estimators=200, random_state=0)

          classifier.fit(X_train, y_train)
          y_pred = classifier.predict(X_test)
          print("Results for Bagging Model : ")
          get_scores(y_test, y_pred)
          ms.get_score_table(y_test, y_pred, map_class)
          get_f1score(y_test, y_pred)

          


def get_model7(X_train, X_test, y_train, y_test):

          clf1= LogisticRegression()
          clf2= RandomForestClassifier()
          clf3= SVC(kernel = 'linear', random_state = 0, probability= True)
          clf4 = AdaBoostClassifier(n_estimators=100, random_state=0)
          clf5= MultinomialNB()
          


          classifier = VotingClassifier(estimators=[  ('lr', clf1), ('SVC', clf3), ('NB', clf5), ('RF', clf2)], voting= 'soft')

          classifier.fit(X_train, y_train)
          y_pred = classifier.predict(X_test)
          print("Results for Voting Model : ")
          get_scores(y_test, y_pred)
          ms.get_score_table(y_test, y_pred, map_class)
          get_f1score(y_test, y_pred)



In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_uni, target, test_size=0.2, random_state=0)
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_uni_bi, target, test_size=0.2, random_state=0)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_uni_bi_tri, target, test_size=0.2, random_state=0)
f1_dict = []
print("For Unigram")
get_model1(X_train, X_test, y_train, y_test)
get_model2(X_train, X_test, y_train, y_test)
get_model3(X_train, X_test, y_train, y_test)
get_model4(X_train, X_test, y_train, y_test)
get_model5(X_train, X_test, y_train, y_test)
get_model6(X_train, X_test, y_train, y_test)
get_model7(X_train, X_test, y_train, y_test)
get_model8(X_train, X_test, y_train, y_test)

print("******************For Bigram*******************")
get_model1(X_train1, X_test1, y_train1, y_test1)
get_model2(X_train1, X_test1, y_train1, y_test1)
get_model3(X_train1, X_test1, y_train1, y_test1)
get_model4(X_train1, X_test1, y_train1, y_test1)
get_model5(X_train1, X_test1, y_train1, y_test1)
get_model6(X_train1, X_test1, y_train1, y_test1)
get_model7(X_train1, X_test1, y_train1, y_test1)
get_model8(X_train1, X_test1, y_train1, y_test1)
print("******************For Trigram*******************")
get_model1(X_train2, X_test2, y_train2, y_test2)
get_model2(X_train2, X_test2, y_train2, y_test2)
get_model3(X_train2, X_test2, y_train2, y_test2)
get_model4(X_train2, X_test2, y_train2, y_test2)
get_model5(X_train2, X_test2, y_train2, y_test2)
get_model6(X_train2, X_test2, y_train2, y_test2)
get_model7(X_train2, X_test2, y_train2, y_test2)
get_model8(X_train2, X_test2, y_train2, y_test2)

For Unigram
Results for SVC model : 
confusion_matrix:
 [[170  29  88]
 [ 47 171  35]
 [ 85  31 202]]
precision: [0.56291391 0.74025974 0.62153846]
recall: [0.59233449 0.67588933 0.63522013]
fscore: [0.57724958 0.70661157 0.62830482]
Accuracy: 0.6328671328671329
+-------+--------------------+--------------------+--------------------+
| class |         f1         |     precision      |       recall       |
+-------+--------------------+--------------------+--------------------+
| Anger | 0.5772495755517827 | 0.5629139072847682 | 0.5923344947735192 |
|  Joy  | 0.7066115702479339 | 0.7402597402597403 | 0.6758893280632411 |
|  Sad  | 0.6283048211508553 | 0.6215384615384615 | 0.6352201257861635 |
+-------+--------------------+--------------------+--------------------+
Results for knn model : 
confusion_matrix:
 [[120  81  86]
 [ 83 114  56]
 [125  74 119]]
precision: [0.36585366 0.42379182 0.4559387 ]
recall: [0.41811847 0.45059289 0.37421384]
fscore: [0.3902439  0.43678161 0.41105354]
Accu